name: Vanilla Desktop
id: vanilla-ci-building
vibversion: 1.0.7

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false
  addincludes: true
  labels:
    maintainer: JustSaft
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update
      - apt install -y sudo

  - name: includes
    type: includes
    includes:
      - kdeconnect-deps.yml

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock

  - name: sysconf-setup
    type: shell
    commands:
      - rsync -a /etc/ /sysconf/

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/share/init.d/010-fsguard.sh

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*